"use client";
import { useState, useEffect, useCallback, useRef } from "react";

const T = {
  bg: "#0D0F14", surface: "#13151C", card: "#1A1D27", border: "#252836",
  text: "#ECEDEF", textSub: "#9B9EA8", muted: "#6B7280",
  accent: "#6366F1", accentBg: "#1E1F3A", green: "#34D399", red: "#F87171",
  yellow: "#FBBF24", amber: "#FBBF24", purple: "#A78BFA",
};

// Common English words that look like tickers but aren't
const IGNORE = new Set([
  "A","I","AM","AN","AS","AT","BE","BY","DO","IF","IN","IS","IT","ME","MY","NO","OF","ON","OR","SO","TO","UP","US","WE",
  "AND","ARE","BUT","CAN","FOR","HAD","HAS","HIM","HIS","HOW","ITS","LET","MAY","NEW","NOT","NOW","ONE","OUR","OUT","PUT",
  "THE","TOO","WAS","WHO","WHY","YET","YOU","ALL","ANY","FEW","OLD","OWN","PER","SAW","SEE","SET","SHE","TOP","TWO","USE",
  "VIA","WAY","YTD","ETF","CEO","CFO","GDP","IPO","LTM","NTM","P&L","YOY","QOQ","ROE","ROI","EPS","FCF","NAV",
  "OPEN","RISK","HIGH","LOW","MUCH","NEXT","ONLY","OVER","PAST","REAL","SAME","SHOW","STAY","TAKE","THAN","THAT","THEM",
  "THEN","THEY","THIS","THUS","THUS","TOLD","UPON","VERY","WELL","WHEN","WITH","YEAR","YOUR","BOND","CASH","DEBT","HOLD",
  "LONG","SELL","STOP","BUY","TAKE","WAIT","WEEK","DAYS","LAST","BOTH","BEST","NEAR","MOST","MORE","LESS","INTO",
  "NYSE","NASDAQ","POST","PRE","RATE","RATE","PLAN","WANT","SAID","WILL","JUST","ALSO","FROM","BEEN","HAVE","WERE","EACH",
  "SOME","LIKE","WHAT","EVEN","MUCH","BACK","ONLY","LOOK","MAKE","GOOD","MANY","COME","CALL","KNOW","GIVE","MOVE",
]);

function extractTickers(text: string): string[] {
  // Match 1-5 uppercase letters optionally preceded by $ sign
  const matches = text.match(/\$?[A-Z]{2,5}\b/g) ?? [];
  const seen = new Set<string>();
  const result: string[] = [];
  for (const m of matches) {
    const sym = m.replace(/^\$/, "");
    if (!IGNORE.has(sym) && !seen.has(sym)) {
      seen.add(sym);
      result.push(sym);
    }
  }
  return result.slice(0, 10);
}

type Briefing = {
  id: string;
  date: string;
  session: "morning" | "evening";
  content: string;
  model: string | null;
  created_at: string;
};

type WatchlistSymbol = { symbol: string };

function fmtDt(iso: string) {
  return new Date(iso).toLocaleString("en-US", { weekday: "long", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" });
}

type Props = { initialBriefing?: { id: string; date: string; session: string; content: string; model: string | null; created_at: string } | null }

export default function BriefingSection({ initialBriefing }: Props) {
  const [briefings, setBriefings] = useState<Briefing[]>([]);
  const [watchlist, setWatchlist] = useState<Set<string>>(new Set());
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState<"morning" | "evening" | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [addedNow, setAddedNow] = useState<Set<string>>(new Set());
  const autoGeneratedRef = useRef(false);

  const load = useCallback(async () => {
    setLoading(true);
    const [briefRes, watchRes] = await Promise.allSettled([
      fetch("/api/briefing").then(r => r.json()),
      fetch("/api/watchlist").then(r => r.json()),
    ]);
    if (briefRes.status === "fulfilled") setBriefings(briefRes.value.briefings ?? []);
    if (watchRes.status === "fulfilled") {
      const syms = (watchRes.value.items ?? []).map((i: WatchlistSymbol) => i.symbol);
      setWatchlist(new Set(syms));
    }
    setLoading(false);
  }, []);

  useEffect(() => { load(); }, [load]);

  // Auto-generate morning brief on page open if none exists for today (runs once only)
  useEffect(() => {
    if (loading || autoGeneratedRef.current) return;
    // Use local date (not UTC) to avoid timezone mismatch around midnight ET
    const todayStr = new Date().toLocaleDateString("en-CA");
    const morning = briefings.find(b => b.session === "morning");
    if (!morning || morning.date !== todayStr) {
      autoGeneratedRef.current = true;
      generate("morning");
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading]);

  async function generate(session: "morning" | "evening") {
    setGenerating(session);
    setError(null);
    const r = await fetch("/api/briefing/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ session }),
    }).catch(() => null);
    if (!r?.ok) {
      const msg = await r?.text().catch(() => "Unknown error") ?? "Unknown error";
      setError(msg);
    } else {
      await load();
    }
    setGenerating(null);
  }

  async function addToWatchlist(symbol: string) {
    setAddedNow(prev => new Set([...prev, symbol]));
    setWatchlist(prev => new Set([...prev, symbol]));
    await fetch("/api/watchlist", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ symbol, source: "briefing", notes: "Mentioned in briefing" }),
    }).catch(() => {});
  }

  const morning = briefings.find(b => b.session === "morning");
  const evening = briefings.find(b => b.session === "evening");
  const todayStr = new Date().toISOString().slice(0, 10);
  const morningIsToday = morning?.date === todayStr;
  const eveningIsToday = evening?.date === todayStr;

  // Extract symbols mentioned across today's briefings
  const todayText = [morning?.content, evening?.content].filter(Boolean).join(" ");
  const mentionedSymbols = todayText ? extractTickers(todayText) : [];
  const untracked = mentionedSymbols.filter(s => !watchlist.has(s));

  return (
    <div>
      {/* Section label */}
      <div style={{ fontSize: "10px", fontWeight: 700, color: T.muted, letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: "12px" }}>
        Daily Briefing
      </div>

      {error && (
        <div style={{ background: "#3B0000", border: "1px solid #F8717144", borderRadius: "8px", padding: "12px 16px", marginBottom: "16px", fontSize: "12px", color: T.red }}>
          {error}
        </div>
      )}

      {loading ? (
        <div style={{ color: T.muted, fontSize: "13px", padding: "40px 0", textAlign: "center" }}>Loading briefings…</div>
      ) : briefings.length === 0 ? (
        <div style={{ background: T.card, border: `1px solid ${T.border}`, borderRadius: "12px", padding: "40px", textAlign: "center" }}>
          <div style={{ fontSize: "32px", marginBottom: "12px" }}>☀</div>
          <div style={{ fontSize: "15px", fontWeight: 600, marginBottom: "8px" }}>No briefings yet</div>
          <div style={{ fontSize: "13px", color: T.muted, marginBottom: "20px" }}>
            Briefings generate automatically at 9 AM (morning) and 4:30 PM (evening) ET weekdays via pg_cron.
            Or generate one now:
          </div>
          <div style={{ display: "flex", gap: "12px", justifyContent: "center" }}>
            <button
              onClick={() => generate("morning")}
              disabled={!!generating}
              style={{ padding: "10px 24px", borderRadius: "8px", background: T.accent, border: "none", color: "#fff", fontSize: "13px", fontWeight: 600, cursor: "pointer", opacity: generating ? 0.6 : 1 }}
            >
              {generating === "morning" ? "Generating morning brief…" : "Generate Morning Brief"}
            </button>
            <button
              onClick={() => generate("evening")}
              disabled={!!generating}
              style={{ padding: "10px 24px", borderRadius: "8px", background: "none", border: `1px solid ${T.border}`, color: T.textSub, fontSize: "13px", fontWeight: 600, cursor: "pointer", opacity: generating ? 0.6 : 1 }}
            >
              {generating === "evening" ? "Generating evening summary…" : "Generate Evening Summary"}
            </button>
          </div>
        </div>
      ) : (
        <>
          {/* Morning + Evening side by side */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }}>
            {/* Morning */}
            <div style={{ background: T.card, border: `1px solid ${morningIsToday ? T.accent + "44" : T.border}`, borderRadius: "12px", padding: "20px" }}>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "14px" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                  <span style={{ fontSize: "18px" }}>☀</span>
                  <div>
                    <div style={{ fontSize: "12px", fontWeight: 700, color: T.yellow }}>MORNING BRIEF</div>
                    {morning && <div style={{ fontSize: "10px", color: T.muted, marginTop: "1px" }}>{fmtDt(morning.created_at)}{morningIsToday ? " · Today" : ""}</div>}
                  </div>
                </div>
                <button
                  onClick={() => generate("morning")}
                  disabled={!!generating}
                  style={{ fontSize: "11px", padding: "4px 10px", borderRadius: "6px", border: `1px solid ${T.border}`, background: "none", color: T.muted, cursor: "pointer", opacity: generating ? 0.5 : 1 }}
                >
                  {generating === "morning" ? "…" : morningIsToday ? "Regen" : "Generate"}
                </button>
              </div>
              {morning ? (
                <div style={{ fontSize: "13px", color: T.textSub, lineHeight: "1.8", whiteSpace: "pre-wrap" }}>{morning.content}</div>
              ) : (
                <div style={{ color: T.muted, fontSize: "13px", padding: "20px 0", textAlign: "center" }}>
                  No morning brief yet today.<br />
                  <span style={{ fontSize: "11px" }}>Auto-generates at 9 AM ET weekdays.</span>
                </div>
              )}
            </div>

            {/* Evening */}
            <div style={{ background: T.card, border: `1px solid ${eveningIsToday ? T.accent + "44" : T.border}`, borderRadius: "12px", padding: "20px" }}>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "14px" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                  <span style={{ fontSize: "18px" }}>🌙</span>
                  <div>
                    <div style={{ fontSize: "12px", fontWeight: 700, color: T.accent }}>EVENING SUMMARY</div>
                    {evening && <div style={{ fontSize: "10px", color: T.muted, marginTop: "1px" }}>{fmtDt(evening.created_at)}{eveningIsToday ? " · Today" : ""}</div>}
                  </div>
                </div>
                <button
                  onClick={() => generate("evening")}
                  disabled={!!generating}
                  style={{ fontSize: "11px", padding: "4px 10px", borderRadius: "6px", border: `1px solid ${T.border}`, background: "none", color: T.muted, cursor: "pointer", opacity: generating ? 0.5 : 1 }}
                >
                  {generating === "evening" ? "…" : eveningIsToday ? "Regen" : "Generate"}
                </button>
              </div>
              {evening ? (
                <div style={{ fontSize: "13px", color: T.textSub, lineHeight: "1.8", whiteSpace: "pre-wrap" }}>{evening.content}</div>
              ) : (
                <div style={{ color: T.muted, fontSize: "13px", padding: "20px 0", textAlign: "center" }}>
                  No evening summary yet today.<br />
                  <span style={{ fontSize: "11px" }}>Auto-generates at 4:30 PM ET weekdays.</span>
                </div>
              )}
            </div>
          </div>

          {/* Symbol suggestions from briefing text */}
          {(mentionedSymbols.length > 0) && (
            <div style={{ marginTop: "20px", background: T.card, border: `1px solid ${T.border}`, borderRadius: "12px", padding: "16px 20px" }}>
              <div style={{ fontSize: "10px", fontWeight: 700, color: T.muted, letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: "10px" }}>
                Symbols Mentioned in Today&apos;s Briefing
              </div>
              <div style={{ fontSize: "11px", color: T.muted, marginBottom: "12px" }}>
                The AI mentioned these tickers. Add any to watchlist → ResearchAgent will score them tomorrow 9 AM.
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "8px" }}>
                {mentionedSymbols.map(sym => {
                  const inList = watchlist.has(sym);
                  const justAdded = addedNow.has(sym);
                  return (
                    <div
                      key={sym}
                      style={{
                        display: "flex", alignItems: "center", gap: "6px",
                        background: inList ? `${T.green}12` : T.surface,
                        border: `1px solid ${inList ? T.green + "44" : T.border}`,
                        borderRadius: "8px", padding: "6px 10px",
                      }}
                    >
                      <span style={{ fontSize: "12px", fontWeight: 700, color: inList ? T.green : T.text }}>{sym}</span>
                      {inList ? (
                        <span style={{ fontSize: "9px", color: T.green, fontWeight: 600 }}>
                          {justAdded ? "Added!" : "Watching"}
                        </span>
                      ) : (
                        <button
                          onClick={() => addToWatchlist(sym)}
                          style={{
                            background: `${T.accent}20`, border: `1px solid ${T.accent}44`,
                            color: T.accent, borderRadius: "4px", padding: "2px 7px",
                            fontSize: "9px", fontWeight: 700, cursor: "pointer",
                          }}
                        >
                          + Watch
                        </button>
                      )}
                    </div>
                  );
                })}
              </div>
              {untracked.length === 0 && mentionedSymbols.length > 0 && (
                <div style={{ marginTop: "10px", fontSize: "11px", color: T.green }}>
                  All mentioned symbols are already in your watchlist.
                </div>
              )}
            </div>
          )}
        </>
      )}

      {/* History */}
      {briefings.length > 2 && (
        <div style={{ marginTop: "24px" }}>
          <div style={{ fontSize: "10px", fontWeight: 700, color: T.muted, letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: "12px" }}>Past Briefings</div>
          <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
            {briefings.slice(2).map(b => (
              <div key={b.id} style={{ background: T.surface, border: `1px solid ${T.border}`, borderRadius: "8px", padding: "12px 16px" }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "6px" }}>
                  <span style={{ fontSize: "11px", fontWeight: 600, color: b.session === "morning" ? T.yellow : T.accent }}>
                    {b.session === "morning" ? "☀ Morning" : "🌙 Evening"} · {b.date}
                  </span>
                  <span style={{ fontSize: "10px", color: T.muted }}>{new Date(b.created_at).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })}</span>
                </div>
                <div style={{ fontSize: "12px", color: T.muted, lineHeight: "1.6" }}>
                  {b.content.slice(0, 200)}…
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
