"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, RefreshCw } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { marketById, PROPERTY_MARKETS, sourcesForMarket, type PropertyMarketId } from "@/lib/property/registry";
import { PT } from "./PropertyPrimitives";

type Observation = { source_key: string; metric_key: string; native_unit: string; value: number | string; as_of: string; revision_state: string };
export default function PropertyMarketData({ marketId }: { marketId: PropertyMarketId }) {
  const market = marketById(marketId); const [payload, setPayload] = useState<any>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  async function load() { setLoading(true); const response = await fetch(`/api/property/overview?market=${marketId}`, { cache: "no-store" }); setPayload(await response.json()); setLoading(false); }
  useEffect(() => { load().catch(() => setLoading(false)); }, [marketId]);
  const grouped = useMemo(() => {
    const map = new Map<string, Observation[]>(); for (const row of payload?.observations ?? []) map.set(row.metric_key, [...(map.get(row.metric_key) ?? []), row]); return map;
  }, [payload]);
  async function collect() { setMessage("Collecting official releases..."); const response = await fetch(`/api/property/collect?market=${marketId}`, { method: "POST" }); const result = await response.json(); setMessage(response.ok ? `${result.results?.filter((r: any) => r.outcome === "success").length ?? 0} source runs completed` : result.error ?? "Collection failed"); await load(); }
  return <div style={{ padding: "28px", maxWidth: "1500px" }}>
    <div style={{ display: "flex", justifyContent: "space-between", gap: "15px", alignItems: "flex-start" }}><div><div style={{ fontSize: "12px", color: PT.accent, fontWeight: 700, letterSpacing: "0.08em" }}>MARKET EXPLORER</div><h1 style={{ margin: "7px 0 6px", fontSize: "24px" }}>{market.label} market pack</h1><div style={{ color: PT.muted, fontSize: "11px" }}>{market.scope}</div></div><button onClick={collect} disabled={loading} style={{ border: `1px solid ${PT.border}`, background: PT.surface, color: PT.textSub, borderRadius: "6px", padding: "8px 11px", fontSize: "11px", cursor: "pointer", display: "flex", alignItems: "center", gap: "6px" }}><RefreshCw size={13} />Refresh official data</button></div>
    <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", margin: "20px 0" }}>{PROPERTY_MARKETS.map(item => <Link key={item.id} href={`/property/markets?market=${item.id}`} style={{ padding: "7px 10px", border: `1px solid ${item.id === marketId ? PT.accent : PT.border}`, borderRadius: "6px", textDecoration: "none", color: item.id === marketId ? PT.accent : PT.textSub, fontSize: "12px" }}>{item.label}</Link>)}</div>
    {message ? <div style={{ color: PT.textSub, fontSize: "11px", marginBottom: "12px" }}>{message}</div> : null}
    {loading ? <div style={{ color: PT.muted, padding: "50px 0" }}>Loading property evidence...</div> : grouped.size === 0 ? <div style={{ border: `1px solid ${PT.border}`, borderRadius: "7px", padding: "42px 18px", color: PT.muted, textAlign: "center", fontSize: "12px" }}>No normalized observations yet for this market. Only active, permitted source adapters can populate these charts.</div> : <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(360px, 1fr))", gap: "12px" }}>{[...grouped].map(([metric, rows]) => { const latest = rows[rows.length - 1]; return <section key={metric} style={{ border: `1px solid ${PT.border}`, borderRadius: "7px", background: PT.surface, overflow: "hidden" }}><div style={{ padding: "13px 15px", borderBottom: `1px solid ${PT.border}`, display: "flex", justifyContent: "space-between" }}><div><strong style={{ fontSize: "12px", color: PT.text }}>{metric.replaceAll("_", " ")}</strong><div style={{ fontSize: "9px", color: PT.muted, marginTop: "3px" }}>{latest.source_key} · {latest.native_unit} · as of {latest.as_of}</div></div><Activity size={14} color={PT.accent} /></div><div style={{ height: "230px", padding: "12px 8px" }}><ResponsiveContainer width="100%" height="100%"><LineChart data={rows}><CartesianGrid stroke={PT.border} vertical={false} /><XAxis dataKey="as_of" tick={{ fill: PT.muted, fontSize: 9 }} minTickGap={35} /><YAxis tick={{ fill: PT.muted, fontSize: 9 }} domain={["auto", "auto"]} /><Tooltip contentStyle={{ background: PT.cardRaised, border: `1px solid ${PT.border}`, borderRadius: "6px", fontSize: "10px" }} /><Line type="monotone" dataKey="value" stroke={PT.accent} dot={false} strokeWidth={2} /></LineChart></ResponsiveContainer></div></section>; })}</div>}
    <section style={{ marginTop: "20px", borderTop: `1px solid ${PT.border}`, paddingTop: "16px" }}><h2 style={{ fontSize: "13px", margin: "0 0 9px" }}>Source status</h2>{sourcesForMarket(marketId).map(source => <div key={source.id} style={{ display: "grid", gridTemplateColumns: "1.2fr .7fr 1.5fr", gap: "10px", padding: "9px 0", borderBottom: `1px solid ${PT.border}`, fontSize: "10px" }}><span style={{ color: PT.text }}>{source.name}</span><span style={{ color: source.state === "active" ? PT.accent : source.state === "deferred" ? PT.red : PT.amber }}>{source.state.replaceAll("_", " ")}</span><span style={{ color: PT.muted }}>{source.role}</span></div>)}</section>
  </div>;
}
