"use client";
import { useEffect, useState } from "react";
import { Sparkles } from "lucide-react";
import { EmptyState, FieldLabel, PT, buttonStyle, fieldStyle } from "./PropertyPrimitives";

type Asset = { id: string; display_label: string; geography_slug: string };
type Evidence = { id: number; observed_on: string; kind: string; provenance: string; payload: { amount: number; sourceLabel?: string; rationale?: string } };
type Reference = { id: number; result_kind: string; horizon_years: number | null; payload: Record<string, unknown>; created_at: string };
const labels: Record<string, string> = { purchase_price: "Purchase price", owner_estimate: "Owner estimate", documented_appraisal: "Documented appraisal", observed_sale: "Observed sale", county_appraised_reference: "County appraisal reference", county_assessed_reference: "County assessed reference", owner_comparable: "Owner comparable" };

export default function ValueIntelligencePanel({ assets }: { assets: Asset[] }) {
  const [assetId, setAssetId] = useState(assets[0]?.id ?? ""); const [evidence, setEvidence] = useState<Evidence[]>([]); const [references, setReferences] = useState<Reference[]>([]); const [market, setMarket] = useState(""); const [currency, setCurrency] = useState("USD"); const [kind, setKind] = useState("purchase_price"); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [amount, setAmount] = useState(""); const [sourceLabel, setSourceLabel] = useState(""); const [deriveReference, setDeriveReference] = useState(true); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { if (!assetId) return; const response = await fetch(`/api/property/value-intelligence?assetId=${encodeURIComponent(assetId)}`, { cache: "no-store" }); const json = await response.json(); if (!response.ok) { setMessage(json.error ?? "Value intelligence unavailable"); return; } setEvidence(json.evidence ?? []); setReferences(json.references ?? []); setMarket(json.market); setCurrency(json.currency ?? "USD"); setMessage(""); }
  useEffect(() => { void load(); }, [assetId]);
  async function addEvidence() { setSaving(true); try { const response = await fetch("/api/property/value-intelligence", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assetId, kind, provenance: kind.includes("county") ? "official_reference" : "owner_entered", observedOn: date, amount, sourceLabel, deriveReference }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error ?? "Could not record evidence"); setAmount(""); setSourceLabel(""); setMessage(json.derived?.state === "unvalidated" ? "Evidence recorded. Index reference and scenarios are unvalidated until calibration matures." : json.derived?.state === "not_requested" ? "Evidence recorded without changing the market-index reference." : "Evidence recorded. A compatible market-index reference is not available for this market/date."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not record evidence"); } finally { setSaving(false); } }
  const latestReference = references.find((item) => item.result_kind === "indexed_reference"); const scenarios = references.filter((item) => item.result_kind === "forecast_scenario").sort((a, b) => Number(a.horizon_years) - Number(b.horizon_years));
  return <section style={{ marginTop: "18px", border: `1px solid ${PT.border}`, borderRadius: "7px", overflow: "hidden" }}>
    <div style={{ padding: "13px 15px", borderBottom: `1px solid ${PT.border}`, display: "flex", gap: "9px", alignItems: "center" }}><Sparkles size={15} color={PT.accent} /><div><h2 style={{ margin: 0, color: PT.text, fontSize: "13px" }}>Value intelligence</h2><div style={{ color: PT.muted, fontSize: "10px", marginTop: "3px" }}>Evidence, index reference, and market-index scenarios stay separate.</div></div></div>
    {!assets.length ? <EmptyState title="Add a property first" detail="Value evidence belongs to an encrypted property record." /> : <div className="property-two-column" style={{ padding: "15px", display: "grid", gridTemplateColumns: "minmax(240px, .85fr) minmax(0, 1.15fr)", gap: "18px" }}>
      <div style={{ display: "grid", gap: "10px", alignContent: "start" }}>
        <FieldLabel label="Property"><select value={assetId} onChange={(event) => setAssetId(event.target.value)} style={fieldStyle}>{assets.map((asset) => <option key={asset.id} value={asset.id}>{asset.display_label}</option>)}</select></FieldLabel>
        <FieldLabel label="Evidence type"><select value={kind} onChange={(event) => setKind(event.target.value)} style={fieldStyle}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></FieldLabel>
        <div className="property-two-column" style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" }}><FieldLabel label="Observed date"><input type="date" value={date} onChange={(event) => setDate(event.target.value)} style={fieldStyle} /></FieldLabel><FieldLabel label={`Amount (${currency})`}><input inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} style={fieldStyle} /></FieldLabel></div>
        <FieldLabel label="Source label"><input value={sourceLabel} onChange={(event) => setSourceLabel(event.target.value)} placeholder="Optional: closing statement" style={fieldStyle} /></FieldLabel>
        <label style={{ display: "flex", alignItems: "flex-start", gap: "7px", color: PT.textSub, fontSize: "10px", lineHeight: 1.45, cursor: "pointer" }}><input type="checkbox" checked={deriveReference} onChange={(event) => setDeriveReference(event.target.checked)} style={{ marginTop: "2px" }} />Use this dated evidence as the base for a market-index reference and 1 / 3 / 5-year scenarios.</label>
        <button type="button" disabled={saving || !amount} onClick={() => void addEvidence()} style={{ ...buttonStyle, opacity: saving || !amount ? .5 : 1 }}>Record value evidence</button>
        {message ? <div style={{ color: PT.amber, fontSize: "10px", lineHeight: 1.45 }}>{message}</div> : null}
      </div>
      <div style={{ minWidth: 0 }}>
        <div style={{ fontSize: "10px", fontWeight: 800, color: PT.muted, marginBottom: "7px" }}>LATEST EVIDENCE</div>
        {evidence.length ? <div style={{ display: "grid", gap: "6px" }}>{evidence.slice(0, 5).map((item) => <div key={item.id} style={{ display: "flex", justifyContent: "space-between", gap: "9px", borderBottom: `1px solid ${PT.border}`, paddingBottom: "6px", color: PT.textSub, fontSize: "10px" }}><span>{labels[item.kind] ?? item.kind} · {item.observed_on}{item.payload.sourceLabel ? ` · ${item.payload.sourceLabel}` : ""}</span><strong style={{ color: PT.text }}>{currency} {Number(item.payload.amount).toLocaleString()}</strong></div>)}</div> : <div style={{ color: PT.muted, fontSize: "11px" }}>No value evidence recorded.</div>}
        <div style={{ marginTop: "15px", fontSize: "10px", fontWeight: 800, color: PT.muted }}>MARKET-INDEX-ADJUSTED REFERENCE</div>
        <div style={{ color: PT.muted, fontSize: "9px", lineHeight: 1.4, marginTop: "4px" }}>Only dated evidence explicitly selected as a reference base is used here.</div>
        {latestReference ? <div style={{ color: PT.textSub, fontSize: "10px", lineHeight: 1.5, marginTop: "6px" }}><strong style={{ color: PT.accent }}>{currency} {Number(latestReference.payload.base).toLocaleString(undefined, { maximumFractionDigits: 0 })}</strong> · {String(latestReference.payload.formula)} · index as of {String(latestReference.payload.indexAsOf)} · unvalidated reference, not an appraisal.</div> : <div style={{ color: PT.muted, fontSize: "10px", marginTop: "6px" }}>{market === "bengaluru" ? "No approved Bengaluru price-index feed is active." : "Record dated evidence that overlaps the local price-index history to create a reference."}</div>}
        <div style={{ marginTop: "15px", fontSize: "10px", fontWeight: 800, color: PT.muted }}>1 / 3 / 5-YEAR INDEX SCENARIOS</div>
        {scenarios.length ? scenarios.map((item) => <div key={item.id} style={{ color: PT.textSub, fontSize: "10px", marginTop: "5px" }}>{item.horizon_years}Y: {currency} {Number(item.payload.lower).toLocaleString(undefined, { maximumFractionDigits: 0 })} – {currency} {Number(item.payload.base).toLocaleString(undefined, { maximumFractionDigits: 0 })} – {currency} {Number(item.payload.upper).toLocaleString(undefined, { maximumFractionDigits: 0 })} · shadow scenario, unvalidated</div>) : <div style={{ color: PT.muted, fontSize: "10px", marginTop: "6px" }}>Scenarios appear only when enough compatible market-index history exists.</div>}
      </div>
    </div>}
  </section>;
}
