blank_issues_enabled: false
contact_links:
  - name: General question
    url: https://github.com/AlexanderAbramovPav/youtube-advisor/discussions
    about: For usage questions or design discussions, please use Discussions instead of Issues.
