import { NextResponse } from "next/server";

// RETIRED (live-trading-hardening P1, 2026-07-07).
//
// This legacy generator wrote to the parallel `trade_queue` table. The canonical
// proposal system is `trade_proposals`, generated by `/api/agents/trader` (which
// the daily `kairos-trader` cron and the Execution Gateway both use). Maintaining
// two proposal tables was a real-money correctness hazard (a trade_queue id could
// be sent to the Gateway, which resolves ids in trade_proposals). All generation
// now goes through `/api/agents/trader`; `trade_queue` is no longer written or read.
//
// The table itself is left in place (not dropped) so historical rows survive; a
// follow-up migration can archive it once verified unused.
export async function POST() {
  return NextResponse.json({
    error: "Retired endpoint. Trade proposals are now generated by /api/agents/trader (writes the canonical trade_proposals table). This legacy trade_queue generator has been removed.",
    use_instead: "/api/agents/trader",
  }, { status: 410 });
}
