-- Restore the live-auto DDL that was applied to production OUT OF BAND as
-- "migrations 139/140" but never committed as files. A clean database rebuilt
-- from migrations was missing these objects, so `lib/trading/autonomous-live.ts`
-- (which calls reserve_live_order_budget_v2 and writes broker_order_events)
-- could not run. This migration is fully idempotent: it is a no-op on the live
-- project (objects already exist) and makes a fresh database reproducible.
--
-- Bodies below are the EXACT production definitions captured via
-- pg_get_functiondef / information_schema on 2026-07-10.

-- 1. trade_proposals autonomous columns (out-of-band 139) ----------------------
ALTER TABLE public.trade_proposals
  ADD COLUMN IF NOT EXISTS execution_mode  text,
  ADD COLUMN IF NOT EXISTS policy_snapshot jsonb,
  ADD COLUMN IF NOT EXISTS auto_run_id     uuid,
  ADD COLUMN IF NOT EXISTS auto_decided_at timestamptz;

-- 2. broker_orders reservation columns (out-of-band 139) ----------------------
ALTER TABLE public.broker_orders
  ADD COLUMN IF NOT EXISTS approved_by_user   boolean,
  ADD COLUMN IF NOT EXISTS estimated_notional numeric,
  ADD COLUMN IF NOT EXISTS currency           text,
  ADD COLUMN IF NOT EXISTS broker_env         text,
  ADD COLUMN IF NOT EXISTS market             text;

-- 3. broker_order_events append-only audit table (out-of-band 140) ------------
CREATE TABLE IF NOT EXISTS public.broker_order_events (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at       timestamptz NOT NULL DEFAULT now(),
  broker_order_id  bigint      NOT NULL,
  proposal_id      bigint,
  event_type       text        NOT NULL,
  broker           text,
  broker_order_ref text,
  filled_qty       numeric,
  remaining_qty    numeric,
  fill_price       numeric,
  raw_payload_hash text,
  actor_kind       text,
  auto_run_id      uuid
);

CREATE INDEX IF NOT EXISTS broker_order_events_order_idx
  ON public.broker_order_events (broker_order_id, created_at DESC);

-- Append-only guard: block UPDATE/DELETE.
CREATE OR REPLACE FUNCTION public.boe_block_mutation()
RETURNS trigger LANGUAGE plpgsql AS $function$
begin raise exception 'broker_order_events is append-only'; end
$function$;

DROP TRIGGER IF EXISTS boe_no_update ON public.broker_order_events;
CREATE TRIGGER boe_no_update
  BEFORE DELETE OR UPDATE ON public.broker_order_events
  FOR EACH ROW EXECUTE FUNCTION boe_block_mutation();

-- RLS: service-role only (evidence table).
ALTER TABLE public.broker_order_events ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='broker_order_events' AND policyname='boe_service_all') THEN
    CREATE POLICY boe_service_all ON public.broker_order_events FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END $$;
REVOKE ALL ON public.broker_order_events FROM anon, authenticated;

-- 4. Atomic live-order budget reservation RPC (out-of-band) --------------------
-- Advisory-locked per market+day; daily trade/notional caps on live BUY only;
-- actor must be owner|autonomous_worker (fails closed); inserts the durable
-- pending broker_orders reservation row.
CREATE OR REPLACE FUNCTION public.reserve_live_order_budget_v2(
  p_proposal_id bigint, p_market text, p_broker text, p_broker_env text,
  p_symbol text, p_side text, p_qty numeric, p_order_type text,
  p_limit_price numeric, p_estimated_notional numeric, p_currency text,
  p_max_daily_trades integer, p_max_daily_notional numeric, p_execution_actor text)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_count int;
  v_sum   numeric;
  v_id    bigint;
  v_approved_by_user boolean;
begin
  -- actor must be explicit; null/unknown fails closed.
  if p_execution_actor not in ('owner', 'autonomous_worker') then
    raise exception 'invalid_execution_actor: must be owner or autonomous_worker'
      using errcode = 'P0001';
  end if;

  v_approved_by_user := (p_execution_actor = 'owner');

  -- Serialize concurrent live orders for the same market+day.
  perform pg_advisory_xact_lock(hashtext(current_date::text || ':' || coalesce(p_market,'')));

  -- Daily caps apply to LIVE BUY orders only. Paper orders and SELL exits are exempt.
  if p_side = 'buy' and p_broker_env = 'live' then
    -- Count all active orders: includes pending_submit, submitted, partially_filled, and
    -- unknown_needs_reconcile so timeouts cannot re-open budget (v1 gap).
    select count(*), coalesce(sum(estimated_notional), 0)
      into v_count, v_sum
      from broker_orders
      where market = p_market
        and broker_env = 'live'
        and side = 'buy'
        and created_at >= date_trunc('day', now())
        and status not in ('error', 'rejected', 'canceled', 'cancelled');

    if p_max_daily_trades is not null and v_count + 1 > p_max_daily_trades then
      raise exception 'daily_trade_limit: % live BUY orders today reaches the daily cap of %',
        v_count, p_max_daily_trades using errcode = 'P0001';
    end if;

    if p_max_daily_notional is not null
       and v_sum + coalesce(p_estimated_notional, 0) > p_max_daily_notional then
      raise exception 'daily_notional_limit: today %/% used, this order % would exceed the daily cap',
        round(v_sum, 2), round(p_max_daily_notional, 2), round(coalesce(p_estimated_notional, 0), 2)
        using errcode = 'P0001';
    end if;
  end if;

  -- Atomically insert the pending broker_orders row (durable reservation).
  insert into broker_orders(
    proposal_id, market, broker, broker_env, symbol, side, qty, order_type,
    limit_price, estimated_notional, currency, status, approved_by_user, submitted_at
  ) values (
    p_proposal_id, p_market, p_broker, p_broker_env, p_symbol, p_side, p_qty, p_order_type,
    p_limit_price, p_estimated_notional, p_currency, 'pending_submit', v_approved_by_user, now()
  )
  returning id into v_id;

  return v_id;
end
$function$;
