-- Owner-curated tradable-universe blocklist. A blocked symbol is never scored
-- (research), never filled (paper/trader), and cannot be ordered (gateway).
-- market: 'us' | 'india' | 'all'. category: free text (e.g. 'owner', 'meme',
-- 'leveraged_etf'). Leveraged/inverse ETFs are ALSO auto-blocked in code.
CREATE TABLE IF NOT EXISTS public.symbol_blocklist (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol      text NOT NULL,
  market      text NOT NULL DEFAULT 'all' CHECK (market IN ('us','india','all')),
  category    text,
  reason      text,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS symbol_blocklist_sym_mkt_uniq
  ON public.symbol_blocklist (upper(symbol), market);

ALTER TABLE public.symbol_blocklist ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='symbol_blocklist' AND policyname='sbl_service_all') THEN
    CREATE POLICY sbl_service_all ON public.symbol_blocklist FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='symbol_blocklist' AND policyname='sbl_owner_read') THEN
    CREATE POLICY sbl_owner_read ON public.symbol_blocklist FOR SELECT TO authenticated
      USING ((auth.jwt() ->> 'email') = 'vterminater@gmail.com');
  END IF;
END $$;
REVOKE ALL ON public.symbol_blocklist FROM anon;
