"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRightLeft, Landmark, MapPinned, ShieldCheck } from "lucide-react";
import { PT, FieldLabel, LocalOnlyNotice, PropertyPageFrame, buttonStyle, fieldStyle, StatCell } from "@/components/property/PropertyPrimitives";

type Profile = { liquidCash?: number; emergencyReserve?: number; nearTermObligations?: number; taxRatePct?: number; planningCurrency?: "USD" | "INR" };
type Watch = { id: string; geography_slug: string; display_label: string; locality_kind: string; locality_reference: string; asset_focus: string; payload: { budget?: number; goal?: string } | null; active: boolean };
type Decision = { id: string; run_kind: string; decision_state: string; created_at: string; result: any };
const num = (value: string) => Number(value || 0);
const money = (value: number | undefined, currency: string) => value == null || !Number.isFinite(value) ? "-" : new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(value);
const statusColor = (state?: string) => state?.startsWith("review") ? PT.accent : state === "outside_policy" ? PT.red : state === "insufficient_evidence" ? PT.amber : PT.blue;

export default function CapitalPlanWorkspace() {
  const [profile, setProfile] = useState<Profile>({ planningCurrency: "USD" });
  const [watches, setWatches] = useState<Watch[]>([]); const [runs, setRuns] = useState<Decision[]>([]);
  const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  const [mortgage, setMortgage] = useState({ balance: "", annualRatePct: "", remainingMonths: "360", proposedPrincipal: "", prepaymentPenalty: "", deductible: false });
  const [asset, setAsset] = useState({ amount: "", years: "5", propertyLower: "", propertyBase: "", propertyUpper: "", marketLower: "", marketBase: "", marketUpper: "" });
  const [watch, setWatch] = useState({ market: "austin", label: "", localityKind: "metro", localityReference: "Austin", assetFocus: "mixed", budget: "", goal: "" });

  async function refresh() {
    setLoading(true); try { const response = await fetch("/api/capital-advisor"); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Capital Plan is unavailable"); setProfile(data.profile?.payload ?? { planningCurrency: "USD" }); setWatches(data.watches ?? []); setRuns(data.runs ?? []); if (!data.encryptionReady) setMessage("Private Capital Plan storage is locked until PROPERTY_DATA_ENCRYPTION_KEY is configured."); } catch (error) { setMessage(error instanceof Error ? error.message : "Capital Plan is unavailable"); } finally { setLoading(false); }
  }
  useEffect(() => { void refresh(); }, []);
  const currency = profile.planningCurrency ?? "USD";
  const liquidityFloor = num(String(profile.emergencyReserve ?? 0)) + num(String(profile.nearTermObligations ?? 0));
  const available = num(String(profile.liquidCash ?? 0));
  const latestMortgage = useMemo(() => runs.find((run) => run.run_kind === "mortgage_prepayment"), [runs]);
  const latestAsset = useMemo(() => runs.find((run) => run.run_kind === "cross_asset_comparison"), [runs]);
  async function post(body: unknown) { const response = await fetch("/api/capital-advisor", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Could not save Capital Plan"); await refresh(); return data; }
  async function saveProfile() { try { await post({ action: "save_profile", profile }); setMessage("Capital Profile saved as a new immutable snapshot."); } catch (error) { setMessage(error instanceof Error ? error.message : "Profile could not be saved"); } }
  async function compareMortgage() { try { await post({ action: "mortgage_compare", input: { availableCash: available, emergencyReserve: num(String(profile.emergencyReserve ?? 0)), nearTermObligations: num(String(profile.nearTermObligations ?? 0)), balance: num(mortgage.balance), annualRatePct: num(mortgage.annualRatePct), remainingMonths: Math.round(num(mortgage.remainingMonths)), proposedPrincipal: num(mortgage.proposedPrincipal), prepaymentPenalty: num(mortgage.prepaymentPenalty), interestDeductible: mortgage.deductible, marginalTaxRatePct: num(String(profile.taxRatePct ?? 0)) } }); setMessage("Mortgage comparison recorded. It has not initiated a lender payment."); } catch (error) { setMessage(error instanceof Error ? error.message : "Mortgage comparison failed"); } }
  async function compareAssets() { try { await post({ action: "cross_asset_compare", input: { availableCash: available, emergencyReserve: num(String(profile.emergencyReserve ?? 0)), nearTermObligations: num(String(profile.nearTermObligations ?? 0)), investmentAmount: num(asset.amount), holdingYears: num(asset.years), propertyRange: { lowerPct: num(asset.propertyLower), basePct: num(asset.propertyBase), upperPct: num(asset.propertyUpper) }, marketRange: { lowerPct: num(asset.marketLower), basePct: num(asset.marketBase), upperPct: num(asset.marketUpper) }, propertyLiquidityRisk: "high", marketLiquidityRisk: "medium", propertyConcentrationPct: 0, marketConcentrationPct: 0, evidenceQuality: "owner_assumption" } }); setMessage("Cross-asset comparison recorded as owner-entered assumptions. It does not read broker accounts or place trades."); } catch (error) { setMessage(error instanceof Error ? error.message : "Comparison failed"); } }
  async function addWatch() { try { await post({ action: "create_watch", ...watch, budget: watch.budget ? num(watch.budget) : null }); setMessage("Area watch saved. ZIP/PIN and Bengaluru local evidence remains unavailable until an approved source contract exists."); setWatch((current) => ({ ...current, label: "", budget: "", goal: "" })); } catch (error) { setMessage(error instanceof Error ? error.message : "Area watch could not be saved"); } }

  return <PropertyPageFrame eyebrow="Cross-workspace planning" title="Capital Plan" description="Private decision support for cash reserves, mortgage principal, property watches, and read-only cross-asset scenarios. It cannot move money, call a lender, or trade." help={{ whatItDoes: "Keeps your inputs encrypted, calculates only deterministic scenarios, and records every result as an immutable decision record.", whatToLookFor: ["Reserve and obligations are hard policy constraints, not return assumptions.", "Property and market ranges are explicitly owner-entered until a comparable evidence contract is approved.", "A review state asks for your review; it is never an automatic action."] }}>
    <div className="property-page-body" style={{ padding: "24px 28px", display: "grid", gap: "22px" }}>
      {message ? <LocalOnlyNotice>{message}</LocalOnlyNotice> : null}
      <section style={{ border: `1px solid ${PT.border}`, borderRadius: "7px", background: PT.surface }}>
        <div style={{ padding: "14px 16px", borderBottom: `1px solid ${PT.border}`, display: "flex", gap: "9px", alignItems: "center" }}><ShieldCheck size={16} color={PT.accent} /><div><strong style={{ fontSize: "13px" }}>Capital Profile</strong><div style={{ fontSize: "10px", color: PT.muted, marginTop: "2px" }}>Owner-entered liquid cash only. Paper cash and broker credentials are never read here.</div></div></div>
        <div className="property-three-column" style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", borderBottom: `1px solid ${PT.border}` }}><StatCell label="LIQUID CASH" value={money(available, currency)} /><StatCell label="CASH FLOOR" value={money(liquidityFloor, currency)} /><StatCell label="AVAILABLE ABOVE FLOOR" value={money(Math.max(0, available - liquidityFloor), currency)} tone={available >= liquidityFloor ? PT.accent : PT.red} /></div>
        <div className="property-three-column" style={{ padding: "16px", display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "12px" }}>
          <FieldLabel label="Planning currency"><select value={currency} onChange={(e) => setProfile({ ...profile, planningCurrency: e.target.value as "USD" | "INR" })} style={fieldStyle}><option value="USD">USD</option><option value="INR">INR</option></select></FieldLabel>
          <FieldLabel label="Liquid cash"><input inputMode="decimal" value={profile.liquidCash ?? ""} onChange={(e) => setProfile({ ...profile, liquidCash: num(e.target.value) })} style={fieldStyle} /></FieldLabel>
          <FieldLabel label="Emergency reserve"><input inputMode="decimal" value={profile.emergencyReserve ?? ""} onChange={(e) => setProfile({ ...profile, emergencyReserve: num(e.target.value) })} style={fieldStyle} /></FieldLabel>
          <FieldLabel label="Near-term obligations"><input inputMode="decimal" value={profile.nearTermObligations ?? ""} onChange={(e) => setProfile({ ...profile, nearTermObligations: num(e.target.value) })} style={fieldStyle} /></FieldLabel>
          <FieldLabel label="Marginal tax rate %"><input inputMode="decimal" value={profile.taxRatePct ?? ""} onChange={(e) => setProfile({ ...profile, taxRatePct: num(e.target.value) })} style={fieldStyle} /></FieldLabel>
          <div style={{ display: "flex", alignItems: "end" }}><button type="button" onClick={() => void saveProfile()} style={buttonStyle}>Save profile</button></div>
        </div>
      </section>
      <section className="property-two-column" style={{ display: "grid", gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)", gap: "22px" }}>
        <div style={{ border: `1px solid ${PT.border}`, borderRadius: "7px", background: PT.surface }}><div style={{ padding: "14px 16px", borderBottom: `1px solid ${PT.border}`, display: "flex", alignItems: "center", gap: "8px" }}><Landmark size={16} color={PT.blue} /><strong style={{ fontSize: "13px" }}>Mortgage principal test</strong></div><div style={{ padding: "16px", display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "12px" }}>
          {[ ["Balance", "balance"], ["Rate %", "annualRatePct"], ["Remaining months", "remainingMonths"], ["Extra principal", "proposedPrincipal"], ["Prepayment penalty", "prepaymentPenalty"] ].map(([label, key]) => <FieldLabel key={key} label={label}><input inputMode="decimal" value={mortgage[key as keyof typeof mortgage] as string} onChange={(e) => setMortgage({ ...mortgage, [key]: e.target.value })} style={fieldStyle} /></FieldLabel>)}
          <label style={{ display: "flex", gap: "7px", alignItems: "center", color: PT.textSub, fontSize: "11px" }}><input type="checkbox" checked={mortgage.deductible} onChange={(e) => setMortgage({ ...mortgage, deductible: e.target.checked })} />Interest deduction assumed</label>
          <button type="button" onClick={() => void compareMortgage()} style={buttonStyle}>Record comparison</button>
        </div>{latestMortgage ? <Result result={latestMortgage.result} currency={currency} /> : null}</div>
        <div style={{ border: `1px solid ${PT.border}`, borderRadius: "7px", background: PT.surface }}><div style={{ padding: "14px 16px", borderBottom: `1px solid ${PT.border}`, display: "flex", alignItems: "center", gap: "8px" }}><ArrowRightLeft size={16} color={PT.blue} /><strong style={{ fontSize: "13px" }}>Property vs market scenario</strong></div><div style={{ padding: "16px", display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "12px" }}>
          {[ ["Amount", "amount"], ["Years", "years"], ["Property low %", "propertyLower"], ["Property base %", "propertyBase"], ["Property high %", "propertyUpper"], ["Market low %", "marketLower"], ["Market base %", "marketBase"], ["Market high %", "marketUpper"] ].map(([label, key]) => <FieldLabel key={key} label={label}><input inputMode="decimal" value={asset[key as keyof typeof asset]} onChange={(e) => setAsset({ ...asset, [key]: e.target.value })} style={fieldStyle} /></FieldLabel>)}
          <button type="button" onClick={() => void compareAssets()} style={buttonStyle}>Record comparison</button>
        </div>{latestAsset ? <Result result={latestAsset.result} currency={currency} /> : null}</div>
      </section>
      <section style={{ border: `1px solid ${PT.border}`, borderRadius: "7px", background: PT.surface }}><div style={{ padding: "14px 16px", borderBottom: `1px solid ${PT.border}`, display: "flex", gap: "8px", alignItems: "center" }}><MapPinned size={16} color={PT.accent} /><div><strong style={{ fontSize: "13px" }}>Area watches</strong><div style={{ color: PT.muted, fontSize: "10px", marginTop: "2px" }}>Metro observations can be shown now. ZIP/PIN and Bengaluru-local monitoring stays unavailable until a permitted data contract exists.</div></div></div><div className="property-three-column" style={{ padding: "16px", display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "12px" }}>
        <FieldLabel label="Market"><select value={watch.market} onChange={(e) => setWatch({ ...watch, market: e.target.value })} style={fieldStyle}><option value="austin">US - Austin</option><option value="phoenix">US - Phoenix</option><option value="bengaluru">India - Bengaluru</option></select></FieldLabel><FieldLabel label="Label"><input value={watch.label} onChange={(e) => setWatch({ ...watch, label: e.target.value })} placeholder="Example: North Austin rentals" style={fieldStyle} /></FieldLabel><FieldLabel label="Locality kind"><select value={watch.localityKind} onChange={(e) => setWatch({ ...watch, localityKind: e.target.value })} style={fieldStyle}><option value="metro">Metro</option><option value="city">City</option><option value="zip">ZIP</option><option value="pin">PIN</option><option value="locality">Locality</option></select></FieldLabel><FieldLabel label="Locality"><input value={watch.localityReference} onChange={(e) => setWatch({ ...watch, localityReference: e.target.value })} style={fieldStyle} /></FieldLabel><FieldLabel label="Asset focus"><select value={watch.assetFocus} onChange={(e) => setWatch({ ...watch, assetFocus: e.target.value })} style={fieldStyle}><option value="mixed">Mixed</option><option value="home">Home</option><option value="rental">Rental</option><option value="land">Land</option></select></FieldLabel><div style={{ display: "flex", alignItems: "end" }}><button type="button" onClick={() => void addWatch()} disabled={!watch.label.trim() || !watch.localityReference.trim()} style={{ ...buttonStyle, opacity: watch.label.trim() && watch.localityReference.trim() ? 1 : .5 }}>Add watch</button></div></div>
        {loading ? <div style={{ padding: "16px", color: PT.muted, fontSize: "11px" }}>Loading private watches...</div> : watches.length ? <div style={{ borderTop: `1px solid ${PT.border}` }}>{watches.map((item) => <div key={item.id} className="property-table-row" style={{ display: "grid", gridTemplateColumns: "1.2fr 1fr .7fr .7fr", gap: "12px", padding: "12px 16px", borderBottom: `1px solid ${PT.border}`, fontSize: "11px" }}><span data-label="WATCH" style={{ color: PT.text }}>{item.display_label}</span><span data-label="AREA" style={{ color: PT.textSub }}>{item.locality_reference}</span><span data-label="MARKET" style={{ color: PT.textSub }}>{item.geography_slug}</span><span data-label="COVERAGE" style={{ color: item.locality_kind === "metro" && item.geography_slug !== "bengaluru" ? PT.accent : PT.amber }}>{item.locality_kind === "metro" && item.geography_slug !== "bengaluru" ? "Metro evidence" : "Contract pending"}</span></div>)}</div> : <div style={{ padding: "16px", color: PT.muted, fontSize: "11px" }}>No area watches yet.</div>}</section>
      <LocalOnlyNotice><strong>Advisor narrator and learning are shadow-only by design.</strong> Capital Plan records structured evidence and decisions now. It does not use an LLM to change a number, rank an allocation, submit a payment, or automatically react to an outcome. Those capabilities remain unavailable until observed outcomes and approved provider contracts exist.</LocalOnlyNotice>
    </div>
  </PropertyPageFrame>;
}

function Result({ result, currency }: { result: any; currency: string }) {
  if (!result) return null;
  return <div style={{ borderTop: `1px solid ${PT.border}`, padding: "13px 16px" }}><div style={{ color: statusColor(result.state), fontSize: "10px", fontWeight: 800, letterSpacing: "0.08em" }}>{String(result.state ?? "result").replaceAll("_", " ").toUpperCase()}</div><div style={{ color: PT.textSub, fontSize: "11px", lineHeight: 1.5, marginTop: "5px" }}>{result.reason}</div>{typeof result.netEstimatedBenefit === "number" ? <div style={{ marginTop: "8px", color: PT.text, fontSize: "12px" }}>Estimated net interest benefit: {money(result.netEstimatedBenefit, currency)} | term reduction: {result.monthsShortened} months</div> : null}{result.propertyTerminalRange ? <div style={{ marginTop: "8px", color: PT.text, fontSize: "12px" }}>Property base: {money(result.propertyTerminalRange.base, currency)} | market base: {money(result.marketTerminalRange.base, currency)}</div> : null}</div>;
}
